project:
  type: default
  output-dir: _site
  lib-dir: libs
  render:
    - StartHere.ipynb
    - Simulation.ipynb
    - Primer.ipynb

format:
  html:
    embed-resources: false
    toc: true

execute:
  enabled: false
